export const FETCH_CHARGING_STATION_START = 'FETCH_CHARGING_STATION_START';
export const FETCH_CHARGING_STATION_SUCCESS = 'FETCH_CHARGING_STATION_SUCCESS';
export const FETCH_CHARGING_STATION_FAIL = 'FETCH_CHARGING_STATION_FAIL';